name: Test Action

on:
  push:
    branches:
      - main  # Runs on every push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print a message
        run: echo "Hello, world!"
